package fileutils;

import dbcomponents.Table;
import exceptions.TestsElsewhereException;

import java.io.IOException;
import java.util.ArrayList;
import java.util.StringJoiner;
import java.io.File;
import java.math.BigInteger;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import javax.xml.bind.DatatypeConverter;

import java.io.FileNotFoundException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

/**
 * A utility class that reads and writes Tables to files. A Singleton class.
 * @author Rjmcf
 */
public class TableFileReadWriter
{
    private static TableFileReadWriter instance;

    // The folder in which all Tables are saved.
    private static String parentDirPath;
    // The file extension with which table files are saved.
    private static String fileExtension;
    // The encoding used to convert between hex and String.
    private static final Charset ENCODING = StandardCharsets.UTF_8;
    // The String used to separate fields in files.
    private static final String FIELD_SEPARATOR = String.valueOf((char)0x1F);

    public static final String SERIALIZATION_FILE_EXT = ".ser";
    public static final String CUSTOM_METHOD_FILE_EXT = ".rjmTable";

    /**
     * Gets the name of the Table from the supplied file name.
     * @param  fName The name of the file in the form <tableName>.<extension>
     * @return       The Table name or null if the file is of the form .<extension>
     *               This file has probably been generated by the file system and
     *               should be disregarded.
     */
    public static String getTableNameFromFileName(String fName)
    {
        String[] parts = fName.split("\\.");
        if (parts.length != 2)
            throw new IllegalArgumentException("File name " + fName + " must be in form <tableName>.<extension>");
        if (parts[0].equals(""))
            return null;
        if (!("." + parts[1]).equals(SERIALIZATION_FILE_EXT) && !("." + parts[1]).equals(CUSTOM_METHOD_FILE_EXT))
            throw new IllegalArgumentException("Invalid file extension ." + parts[1] + " for table files");

        return parts[0];
    }

    /**
     * Writes the given table to a file, using the chosen method.
     * @param  t           The Table to write.
     * @throws IOException If an io exception occurred.
     */
    public static void writeToFile(Table t, String pDP, boolean useSerialization) throws IOException
    {
        parentDirPath = pDP;
        fileExtension = useSerialization ? SERIALIZATION_FILE_EXT : CUSTOM_METHOD_FILE_EXT;
        if (useSerialization)
            serWriteToFile(t);
        else
            rjmWriteToFile(t);
    }

    /**
     * Reads a table from a file, using the chosen method.
     * @param  name        The name of the table to be read.
     * @return             The Table instance that has been loaded.
     * @throws IOException If an io exception occurred.
     */
    public static Table readFromFile(String name, String pDP, boolean useSerialization) throws IOException
    {
        parentDirPath = pDP;
        fileExtension = useSerialization ? SERIALIZATION_FILE_EXT : CUSTOM_METHOD_FILE_EXT;
        if (useSerialization)
            return serReadFromFile(name);
        else
            return rjmReadFromFile(name);
    }


    private static void serWriteToFile(Table t) throws IOException
    {
        String fPath = parentDirPath + t.getName() + fileExtension;
        // Need to make sure that the parent directories exist first.
        FileUtil.makeParentDirsIfNeeded(fPath);
        try(FileOutputStream fileOut = new FileOutputStream(fPath);
            ObjectOutputStream out = new ObjectOutputStream(fileOut);)
        {
            // This requires both Table and Record to implement Serializable.
            out.writeObject(t);
        }
    }

    private static Table serReadFromFile(String tableName) throws IOException
    {
        Table t = null;
        try
        {
            FileInputStream fileIn = new FileInputStream(parentDirPath + tableName + fileExtension);
            ObjectInputStream in = new ObjectInputStream(fileIn);
            // This requires both Table and Record to implement Serializable.
            t = (Table) in.readObject();
            in.close();
            fileIn.close();
            return t;
        }
        catch (FileNotFoundException f)
        {
            throw new IllegalArgumentException("Table " + tableName + " file not found");
        }
        catch (ClassNotFoundException c)
        {
            throw new Error("Table class not found");
        }
    }

    private static void rjmWriteToFile(Table t) throws IOException
    {
        String[][] tableData = t.getTableData();

        // The lines to write.
        String[] lines = new String[tableData.length-1];
        StringJoiner joiner = new StringJoiner(FIELD_SEPARATOR);

        // Build the line to print for each row.
        for (int row = 1; row < tableData.length; row++)
        {
            String[] rowFields = tableData[row];
            joiner = new StringJoiner(FIELD_SEPARATOR);
            for (int f = 0; f < rowFields.length; f++)
            {
                // We convert to hex to allow strange characters in these fields.
                joiner.add(convertStringToHex(rowFields[f]));
            }
            lines[row - 1] = joiner.toString();
        }

        String filePath = parentDirPath + t.getName() + fileExtension;
        FileUtil.writeFile(filePath, lines);
    }

    private static Table rjmReadFromFile(String name) throws IOException
    {
        ArrayList<String> lines = FileUtil.readFile(parentDirPath + name + fileExtension);
        String[][] tableData = new String[lines.size()][];
        for (int row = 0; row < lines.size(); row++)
        {
            tableData[row] = lines.get(row).split(FIELD_SEPARATOR);
            for (int col = 0; col < tableData[row].length; col++)
                tableData[row][col] = convertHexToString(tableData[row][col]);
        }
        return Table.createTableFromData(name, tableData);
    }

    private static String convertHexToString(String h)
    {
        byte[] bytes = DatatypeConverter.parseHexBinary(h);
        return new String(bytes, ENCODING);
    }

    private static String convertStringToHex(String s)
    {
        String result = String.format("%x", new BigInteger(1, s.getBytes(ENCODING)));
        // Remember to add a leading "0" if we need it.
        return result.length() % 2 == 0 ? result : "0" + result;
    }

    /**
     * Runs the tests on this class.
     * @param args Command line arguments.
     */
    public static void main(String[] args)
    {
        throw new TestsElsewhereException("TableFileReadWriter", "Table");
    }

    /**
     * Deletes the specified directory.
     * @param file The name of the directory to be deleted.
     */
    public static void deleteDir(File file)
    {
        File[] contents = file.listFiles();
        if (contents != null) {
            for (File f : contents) {
                deleteDir(f);
            }
        }
        file.delete();
    }
}
