name: Run All Tests
on: 
  workflow_dispatch:
  push:
jobs:
  Run-All-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run all the tests
        run: |
          make -s runTests DISABLE_INTERACTIVITY=1
